version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: gym-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: gym-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gymdb
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: gym-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:

